// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

// <auto-generated/>

#nullable disable

using System;
using System.ComponentModel;

namespace Microsoft.Azure.Chaos.ArmGatewayService.Resources.Models.Preview.V2026_05_01_preview
{
    /// <summary> The status of a scenario configuration validation (execution plan generation and validation). </summary>
    public readonly partial struct ScenarioValidationState : IEquatable<ScenarioValidationState>
    {
        private readonly string _value;

        /// <summary> Initializes a new instance of <see cref="ScenarioValidationState"/>. </summary>
        /// <exception cref="ArgumentNullException"> <paramref name="value"/> is null. </exception>
        public ScenarioValidationState(string value)
        {
            _value = value ?? throw new ArgumentNullException(nameof(value));
        }

        private const string ResolvingValue = "Resolving";
        private const string GeneratingValue = "Generating";
        private const string ValidatingValue = "Validating";
        private const string AcceptedValue = "Accepted";
        private const string NotStartedValue = "NotStarted";
        private const string RequiresAttentionValue = "RequiresAttention";
        private const string NoResolvedResourcesValue = "NoResolvedResources";
        private const string SucceededValue = "Succeeded";

        /// <summary> The resource selectors are being resolved. </summary>
        public static ScenarioValidationState Resolving { get; } = new ScenarioValidationState(ResolvingValue);
        /// <summary> The execution plan is being generated. </summary>
        public static ScenarioValidationState Generating { get; } = new ScenarioValidationState(GeneratingValue);
        /// <summary> The execution plan is being validated. </summary>
        public static ScenarioValidationState Validating { get; } = new ScenarioValidationState(ValidatingValue);
        /// <summary> The validation request has been accepted. </summary>
        public static ScenarioValidationState Accepted { get; } = new ScenarioValidationState(AcceptedValue);
        /// <summary> The validation has not started. </summary>
        public static ScenarioValidationState NotStarted { get; } = new ScenarioValidationState(NotStartedValue);
        /// <summary> The validation completed but the configuration requires attention (terminal failure). </summary>
        public static ScenarioValidationState RequiresAttention { get; } = new ScenarioValidationState(RequiresAttentionValue);
        /// <summary> The validation resolved no target resources (terminal failure). </summary>
        public static ScenarioValidationState NoResolvedResources { get; } = new ScenarioValidationState(NoResolvedResourcesValue);
        /// <summary> The validation succeeded (terminal success). </summary>
        public static ScenarioValidationState Succeeded { get; } = new ScenarioValidationState(SucceededValue);

        /// <summary> Determines if two <see cref="ScenarioValidationState"/> values are the same. </summary>
        public static bool operator ==(ScenarioValidationState left, ScenarioValidationState right) => left.Equals(right);
        /// <summary> Determines if two <see cref="ScenarioValidationState"/> values are not the same. </summary>
        public static bool operator !=(ScenarioValidationState left, ScenarioValidationState right) => !left.Equals(right);
        /// <summary> Converts a string to a <see cref="ScenarioValidationState"/>. </summary>
        public static implicit operator ScenarioValidationState(string value) => new ScenarioValidationState(value);

        /// <inheritdoc />
        [EditorBrowsable(EditorBrowsableState.Never)]
        public override bool Equals(object obj) => obj is ScenarioValidationState other && Equals(other);
        /// <inheritdoc />
        public bool Equals(ScenarioValidationState other) => string.Equals(_value, other._value, StringComparison.InvariantCultureIgnoreCase);

        /// <inheritdoc />
        [EditorBrowsable(EditorBrowsableState.Never)]
        public override int GetHashCode() => _value != null ? StringComparer.InvariantCultureIgnoreCase.GetHashCode(_value) : 0;
        /// <inheritdoc />
        public override string ToString() => _value;
    }
}
