// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

// <auto-generated/>

#nullable disable

using System;
using System.Collections.Generic;
using System.Text.Json;
using Azure.Core;

namespace Microsoft.Azure.Chaos.ArmGatewayService.Resources.Models.Preview.V2026_05_01_preview
{
    /// <summary> Properties of a scenario run resource (scenarios/{scenario}/runs/{runId}). </summary>
    public partial class ScenarioRunProperties : IUtf8JsonSerializable
    {
        /// <summary> The current run status. </summary>
        public ScenarioRunState? Status { get; }
        /// <summary> The UTC time the run started. </summary>
        public DateTimeOffset? StartTime { get; }
        /// <summary> The UTC time the run reached a terminal state. </summary>
        public DateTimeOffset? EndTime { get; }
        /// <summary> System/infrastructure errors. </summary>
        public IReadOnlyList<ScenarioError> Errors { get; }
        /// <summary> Business/action execution errors. </summary>
        public IReadOnlyList<ScenarioExecutionError> ExecutionErrors { get; }
        /// <summary> The resources targeted by the run. </summary>
        public IReadOnlyList<ScenarioRunResource> Resources { get; }
        /// <summary> The executed scenario-run JSON. </summary>
        public string ScenarioRunJson { get; }
        /// <summary> A human-readable summary of the run outcome. </summary>
        public string Summary { get; }

        void IUtf8JsonSerializable.Write(Utf8JsonWriter writer)
        {
            writer.WriteStartObject();
            if (Optional.IsDefined(Status))
            {
                writer.WritePropertyName("status"u8);
                writer.WriteStringValue(Status.Value.ToString());
            }
            if (Optional.IsDefined(StartTime))
            {
                writer.WritePropertyName("startTime"u8);
                writer.WriteStringValue(StartTime.Value, "O");
            }
            if (Optional.IsDefined(EndTime))
            {
                writer.WritePropertyName("endTime"u8);
                writer.WriteStringValue(EndTime.Value, "O");
            }
            if (Optional.IsCollectionDefined(Errors))
            {
                writer.WritePropertyName("errors"u8);
                writer.WriteStartArray();
                foreach (var item in Errors)
                {
                    writer.WriteObjectValue(item);
                }
                writer.WriteEndArray();
            }
            if (Optional.IsCollectionDefined(ExecutionErrors))
            {
                writer.WritePropertyName("executionErrors"u8);
                writer.WriteStartArray();
                foreach (var item in ExecutionErrors)
                {
                    writer.WriteObjectValue(item);
                }
                writer.WriteEndArray();
            }
            if (Optional.IsCollectionDefined(Resources))
            {
                writer.WritePropertyName("resources"u8);
                writer.WriteStartArray();
                foreach (var item in Resources)
                {
                    writer.WriteObjectValue(item);
                }
                writer.WriteEndArray();
            }
            if (Optional.IsDefined(ScenarioRunJson))
            {
                writer.WritePropertyName("scenarioRunJson"u8);
                writer.WriteStringValue(ScenarioRunJson);
            }
            if (Optional.IsDefined(Summary))
            {
                writer.WritePropertyName("summary"u8);
                writer.WriteStringValue(Summary);
            }
            writer.WriteEndObject();
        }
    }
}
