// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

// <auto-generated/>

#nullable disable

using System;
using System.ComponentModel;

namespace Microsoft.Azure.Chaos.ArmGatewayService.Resources.Models.Preview.V2026_05_01_preview
{
    /// <summary> The status of a scenario run. For execution-mode runs, Succeeded, Failed, and Canceled are terminal. </summary>
    public readonly partial struct ScenarioRunState : IEquatable<ScenarioRunState>
    {
        private readonly string _value;

        /// <summary> Initializes a new instance of <see cref="ScenarioRunState"/>. </summary>
        /// <exception cref="ArgumentNullException"> <paramref name="value"/> is null. </exception>
        public ScenarioRunState(string value)
        {
            _value = value ?? throw new ArgumentNullException(nameof(value));
        }

        private const string QueuedValue = "Queued";
        private const string ResolvingValue = "Resolving";
        private const string GeneratingValue = "Generating";
        private const string ValidatingValue = "Validating";
        private const string ValidationSucceededValue = "ValidationSucceeded";
        private const string StartingValue = "Starting";
        private const string PreparingValue = "Preparing";
        private const string RunningValue = "Running";
        private const string CleaningUpValue = "CleaningUp";
        private const string CancelingValue = "Canceling";
        private const string CanceledValue = "Canceled";
        private const string SucceededValue = "Succeeded";
        private const string FailedValue = "Failed";

        /// <summary> The run is queued. </summary>
        public static ScenarioRunState Queued { get; } = new ScenarioRunState(QueuedValue);
        /// <summary> The resource selectors are being resolved. </summary>
        public static ScenarioRunState Resolving { get; } = new ScenarioRunState(ResolvingValue);
        /// <summary> The execution plan is being generated. </summary>
        public static ScenarioRunState Generating { get; } = new ScenarioRunState(GeneratingValue);
        /// <summary> The execution plan is being validated. </summary>
        public static ScenarioRunState Validating { get; } = new ScenarioRunState(ValidatingValue);
        /// <summary> Validation succeeded and the run is proceeding to execution. </summary>
        public static ScenarioRunState ValidationSucceeded { get; } = new ScenarioRunState(ValidationSucceededValue);
        /// <summary> The run is starting. </summary>
        public static ScenarioRunState Starting { get; } = new ScenarioRunState(StartingValue);
        /// <summary> The run is preparing target resources. </summary>
        public static ScenarioRunState Preparing { get; } = new ScenarioRunState(PreparingValue);
        /// <summary> The run is executing faults. </summary>
        public static ScenarioRunState Running { get; } = new ScenarioRunState(RunningValue);
        /// <summary> The run is cleaning up target resources. </summary>
        public static ScenarioRunState CleaningUp { get; } = new ScenarioRunState(CleaningUpValue);
        /// <summary> Cancellation has been requested and is in progress. </summary>
        public static ScenarioRunState Canceling { get; } = new ScenarioRunState(CancelingValue);
        /// <summary> The run was canceled (terminal). </summary>
        public static ScenarioRunState Canceled { get; } = new ScenarioRunState(CanceledValue);
        /// <summary> The run succeeded (terminal). </summary>
        public static ScenarioRunState Succeeded { get; } = new ScenarioRunState(SucceededValue);
        /// <summary> The run failed (terminal). </summary>
        public static ScenarioRunState Failed { get; } = new ScenarioRunState(FailedValue);

        /// <summary> Determines if two <see cref="ScenarioRunState"/> values are the same. </summary>
        public static bool operator ==(ScenarioRunState left, ScenarioRunState right) => left.Equals(right);
        /// <summary> Determines if two <see cref="ScenarioRunState"/> values are not the same. </summary>
        public static bool operator !=(ScenarioRunState left, ScenarioRunState right) => !left.Equals(right);
        /// <summary> Converts a string to a <see cref="ScenarioRunState"/>. </summary>
        public static implicit operator ScenarioRunState(string value) => new ScenarioRunState(value);

        /// <inheritdoc />
        [EditorBrowsable(EditorBrowsableState.Never)]
        public override bool Equals(object obj) => obj is ScenarioRunState other && Equals(other);
        /// <inheritdoc />
        public bool Equals(ScenarioRunState other) => string.Equals(_value, other._value, StringComparison.InvariantCultureIgnoreCase);

        /// <inheritdoc />
        [EditorBrowsable(EditorBrowsableState.Never)]
        public override int GetHashCode() => _value != null ? StringComparer.InvariantCultureIgnoreCase.GetHashCode(_value) : 0;
        /// <inheritdoc />
        public override string ToString() => _value;
    }
}
