// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

// <auto-generated/>

#nullable disable

using System.Collections.Generic;
using System.Text.Json;
using Azure.Core;

namespace Microsoft.Azure.Chaos.ArmGatewayService.Resources.Models.Preview.V2026_05_01_preview
{
    /// <summary> A system/infrastructure error entry (the `errors` channel). </summary>
    public partial class ScenarioError : IUtf8JsonSerializable
    {
        public string Code { get; }
        public string Message { get; }

        void IUtf8JsonSerializable.Write(Utf8JsonWriter writer)
        {
            writer.WriteStartObject();
            if (Optional.IsDefined(Code))
            {
                writer.WritePropertyName("code"u8);
                writer.WriteStringValue(Code);
            }
            if (Optional.IsDefined(Message))
            {
                writer.WritePropertyName("message"u8);
                writer.WriteStringValue(Message);
            }
            writer.WriteEndObject();
        }
    }

    /// <summary> A validation business error (the `validationErrors` channel): permission/resource-state detail with remediation. </summary>
    public partial class ScenarioValidationError : IUtf8JsonSerializable
    {
        public string Code { get; }
        public string Message { get; }
        public string ResourceId { get; }
        public IReadOnlyList<string> RecommendedRoles { get; }

        void IUtf8JsonSerializable.Write(Utf8JsonWriter writer)
        {
            writer.WriteStartObject();
            if (Optional.IsDefined(Code))
            {
                writer.WritePropertyName("code"u8);
                writer.WriteStringValue(Code);
            }
            if (Optional.IsDefined(Message))
            {
                writer.WritePropertyName("message"u8);
                writer.WriteStringValue(Message);
            }
            if (Optional.IsDefined(ResourceId))
            {
                writer.WritePropertyName("resourceId"u8);
                writer.WriteStringValue(ResourceId);
            }
            if (Optional.IsCollectionDefined(RecommendedRoles))
            {
                writer.WritePropertyName("recommendedRoles"u8);
                writer.WriteStartArray();
                foreach (var item in RecommendedRoles)
                {
                    writer.WriteStringValue(item);
                }
                writer.WriteEndArray();
            }
            writer.WriteEndObject();
        }
    }

    /// <summary> A run business/action error (the `executionErrors` channel). </summary>
    public partial class ScenarioExecutionError : IUtf8JsonSerializable
    {
        public string Code { get; }
        public string Message { get; }
        public string ResourceId { get; }

        void IUtf8JsonSerializable.Write(Utf8JsonWriter writer)
        {
            writer.WriteStartObject();
            if (Optional.IsDefined(Code))
            {
                writer.WritePropertyName("code"u8);
                writer.WriteStringValue(Code);
            }
            if (Optional.IsDefined(Message))
            {
                writer.WritePropertyName("message"u8);
                writer.WriteStringValue(Message);
            }
            if (Optional.IsDefined(ResourceId))
            {
                writer.WritePropertyName("resourceId"u8);
                writer.WriteStringValue(ResourceId);
            }
            writer.WriteEndObject();
        }
    }
}
