// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

// <auto-generated/>

#nullable disable

using System.Collections.Generic;
using System.Text.Json;
using Azure.Core;

namespace Microsoft.Azure.Chaos.ArmGatewayService.Resources.Models.Preview.V2026_05_01_preview
{
    /// <summary> An element of the run `resources` array: a resource targeted by the run. </summary>
    public partial class ScenarioRunResource : IUtf8JsonSerializable
    {
        /// <summary> The ARM id of the targeted resource. </summary>
        public string ResourceId { get; }
        /// <summary> The target type applied to the resource. </summary>
        public string TargetType { get; }
        /// <summary> The selector expressions that resolved to this resource. </summary>
        public IReadOnlyList<string> Selectors { get; }

        void IUtf8JsonSerializable.Write(Utf8JsonWriter writer)
        {
            writer.WriteStartObject();
            if (Optional.IsDefined(ResourceId))
            {
                writer.WritePropertyName("resourceId"u8);
                writer.WriteStringValue(ResourceId);
            }
            if (Optional.IsDefined(TargetType))
            {
                writer.WritePropertyName("targetType"u8);
                writer.WriteStringValue(TargetType);
            }
            if (Optional.IsCollectionDefined(Selectors))
            {
                writer.WritePropertyName("selectors"u8);
                writer.WriteStartArray();
                foreach (var item in Selectors)
                {
                    writer.WriteStringValue(item);
                }
                writer.WriteEndArray();
            }
            writer.WriteEndObject();
        }
    }
}
