// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

// <auto-generated/>

#nullable disable

using System;
using System.Collections.Generic;
using System.Text.Json;
using Azure.Core;

namespace Microsoft.Azure.Chaos.ArmGatewayService.Resources.Models.Preview.V2026_05_01_preview
{
    /// <summary> Properties of a scenario configuration validation resource (validations/latest). </summary>
    public partial class ValidationProperties : IUtf8JsonSerializable
    {
        /// <summary> The current validation status. </summary>
        public ScenarioValidationState? Status { get; }
        /// <summary> The UTC time the validation started. </summary>
        public DateTimeOffset? StartTime { get; }
        /// <summary> The UTC time the validation reached a terminal state. </summary>
        public DateTimeOffset? EndTime { get; }
        /// <summary> The generated execution plan that the next execution of this configuration will run. </summary>
        public string ExecutionPlanJson { get; }
        /// <summary> System/infrastructure errors. </summary>
        public IReadOnlyList<ScenarioError> Errors { get; }
        /// <summary> Business errors: permission errors, resource-state errors, remediation data, and recommended roles. </summary>
        public IReadOnlyList<ScenarioValidationError> ValidationErrors { get; }

        void IUtf8JsonSerializable.Write(Utf8JsonWriter writer)
        {
            writer.WriteStartObject();
            if (Optional.IsDefined(Status))
            {
                writer.WritePropertyName("status"u8);
                writer.WriteStringValue(Status.Value.ToString());
            }
            if (Optional.IsDefined(StartTime))
            {
                writer.WritePropertyName("startTime"u8);
                writer.WriteStringValue(StartTime.Value, "O");
            }
            if (Optional.IsDefined(EndTime))
            {
                writer.WritePropertyName("endTime"u8);
                writer.WriteStringValue(EndTime.Value, "O");
            }
            if (Optional.IsDefined(ExecutionPlanJson))
            {
                writer.WritePropertyName("executionPlanJson"u8);
                writer.WriteStringValue(ExecutionPlanJson);
            }
            if (Optional.IsCollectionDefined(Errors))
            {
                writer.WritePropertyName("errors"u8);
                writer.WriteStartArray();
                foreach (var item in Errors)
                {
                    writer.WriteObjectValue(item);
                }
                writer.WriteEndArray();
            }
            if (Optional.IsCollectionDefined(ValidationErrors))
            {
                writer.WritePropertyName("validationErrors"u8);
                writer.WriteStartArray();
                foreach (var item in ValidationErrors)
                {
                    writer.WriteObjectValue(item);
                }
                writer.WriteEndArray();
            }
            writer.WriteEndObject();
        }
    }
}
