// build.mjs — regenerates the ENTIRE committed runtime-bundle tree under `dist/`.
//
// This is the SINGLE deterministic producer of every committed file under
// `dist/` — both each surface's `index.js` bundle AND the `README.md` beside it —
// so the release/PR "dist integrity" gate is EFFECTIVE and EXACT: a clean
// `npm run build` into an empty `dist/` must reproduce the committed tree
// file-for-file (paths, modes, and blob hashes).
//
// Both platform bundles are produced by `esbuild`, bundling each adapter's real
// entrypoint (`packages/action-github/src/index.ts`,
// `packages/task-azure-pipelines/src/index.ts`) together with its runtime
// dependencies (`@actions/core`, `@azure/identity`, `azure-pipelines-task-lib`,
// etc.) into a single self-contained CommonJS file so the root Action / task can
// run with no `node_modules` install step (R1). `import.meta.url` (used by each
// entrypoint's main-module guard) is not natively expressible in CommonJS, so it
// is rewritten at build time to an equivalent `pathToFileURL(__filename).href`
// expression via esbuild's `define` + `banner` (deterministic, no behavior
// change vs. the ESM source).
//
// `target: 'node20'` keeps both bundles compatible with the OLDEST runtime
// either surface declares: the Azure Pipelines task retains `Node20_1` as its
// Server-compatible fallback while preferring `Node24`; Node24 runs
// Node20-targeted output fine.
//
// All content is LF-only with a single trailing newline (byte-stable across
// platforms; `.gitattributes` also pins these paths to `eol=lf`).
//
// Run: `npm run build`

import { mkdirSync, writeFileSync, rmSync, readFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';
import esbuild from 'esbuild';

const REPO_ROOT = join(dirname(fileURLToPath(import.meta.url)), '..');

/** Normalize esbuild output to LF-only with exactly one trailing newline. */
function normalizeLf(text) {
  return text.replace(/\r\n/g, '\n').replace(/\n*$/, '\n');
}

/**
 * Bundle a platform adapter entrypoint into a single self-contained CommonJS
 * file (R1). Bundles ALL runtime dependencies (no external `node_modules`
 * needed at run time); only Node built-ins stay external (implicit — esbuild's
 * `platform: 'node'` never bundles built-ins).
 */
async function bundleAdapter(entryPoint) {
  const result = await esbuild.build({
    entryPoints: [entryPoint],
    bundle: true,
    platform: 'node',
    target: 'node20',
    format: 'cjs',
    write: false,
    logLevel: 'silent',
    // `import.meta.url` has no CJS equivalent; esbuild's `define` substitutes a
    // reference resolved by the `banner` below, so the main-module guard (only
    // run `main()` when executed directly, never on import from tests) behaves
    // identically to the ESM source under `tsx`/`node --experimental-strip-types`.
    define: { 'import.meta.url': 'importMetaUrl' },
    banner: { js: 'const importMetaUrl = require("url").pathToFileURL(__filename).href;' },
  });
  const [out] = result.outputFiles;
  return normalizeLf(out.text);
}

const ACTION_README =
  `# \`dist/github-action/\` — committed GitHub Action bundle\n` +
  `\n` +
  `This directory holds the **reproducibly built, committed** runtime bundle that\n` +
  `the root [\`action.yml\`](../../action.yml) executes with the \`node24\` runtime\n` +
  `(VF16, VF17, D19). GitHub Marketplace consumers run this bundle directly, so it\n` +
  `is checked in rather than built on the fly.\n` +
  `\n` +
  `- **Source:** \`packages/action-github\` (thin \`@actions/core\` adapter over the\n` +
  `  shared core in \`packages/core\`).\n` +
  `- **Build:** produced by \`npm run build\` (\`scripts/build.mjs\`), which bundles\n` +
  `  \`packages/action-github/src/index.ts\` and its runtime dependencies\n` +
  `  (\`@actions/core\`, \`@azure/identity\`) into this single self-contained\n` +
  `  CommonJS file via \`esbuild\`, and is verified by a \`dist\`-integrity check\n` +
  `  that fails the build if the committed tree does not match a clean rebuild\n` +
  `  file-for-file (supply-chain hardening, D18).\n` +
  `\n` +
  `Both \`index.js\` and this \`README.md\` are generated by \`scripts/build.mjs\` so the\n` +
  `exact-tree integrity gate reproduces the whole directory.\n`;

const TASK_README =
  `# \`dist/azure-pipelines-task/\` — committed Azure Pipelines task bundle\n` +
  `\n` +
  `This directory holds the **reproducibly built** runtime bundle for the Azure\n` +
  `Pipelines task. The OneBranch official pipeline copies this bundle into the task\n` +
  `folder under [\`azure-pipelines-extension/\`](../../azure-pipelines-extension/)\n` +
  `and packages it into the signed VSIX.\n` +
  `\n` +
  `- **Source:** \`packages/task-azure-pipelines\` (thin \`azure-pipelines-task-lib\`\n` +
  `  adapter over the shared core in \`packages/core\`).\n` +
  `- **Runtime:** the task prefers the \`Node24\` execution handler and retains\n` +
  `  \`Node20_1\` as a compatibility fallback for Azure DevOps Server agents.\n` +
  `- **Build:** produced by \`npm run build\` (\`scripts/build.mjs\`), which bundles\n` +
  `  \`packages/task-azure-pipelines/src/index.ts\` and its runtime dependencies\n` +
  `  (\`@azure/identity\`, \`azure-pipelines-task-lib\`) into this single\n` +
  `  self-contained CommonJS file via \`esbuild\`, so the \`dist\`-integrity gate\n` +
  `  reproduces the whole directory.\n`;

async function main() {
  // The COMPLETE committed dist tree. Every committed file under dist/ is
  // produced here so the exact-tree integrity gate matches after a clean rebuild.
  const FILES = [
    {
      path: 'dist/github-action/index.js',
      content: await bundleAdapter(join(REPO_ROOT, 'packages/action-github/src/index.ts')),
    },
    { path: 'dist/github-action/README.md', content: ACTION_README },
    {
      path: 'dist/azure-pipelines-task/index.js',
      content: await bundleAdapter(join(REPO_ROOT, 'packages/task-azure-pipelines/src/index.ts')),
    },
    { path: 'dist/azure-pipelines-task/README.md', content: TASK_README },
  ];

  // Build into a clean dist/ so a stale file the build no longer emits cannot
  // linger (the release/PR gate additionally rebuilds into an empty dir).
  rmSync(join(REPO_ROOT, 'dist'), { recursive: true, force: true });
  for (const file of FILES) {
    const full = join(REPO_ROOT, file.path);
    mkdirSync(dirname(full), { recursive: true });
    writeFileSync(full, file.content, 'utf8');
    console.log(`Wrote ${file.path} (${readFileSync(full, 'utf8').length} bytes)`);
  }
}

await main();
