// build.mjs — regenerates the ENTIRE committed runtime-bundle tree under `dist/`.
//
// E1 has no adapter runtime yet, so each surface's committed bundle is a fail-fast
// placeholder (E3 replaces the Action bundle; E4 replaces the task bundle). This
// script is the SINGLE deterministic producer of every committed file under
// `dist/` — both the `index.js` bundle AND the `README.md` beside it — so the
// release/PR "dist integrity" gate is EFFECTIVE and EXACT: a clean `npm run build`
// into an empty `dist/` must reproduce the committed tree file-for-file (paths,
// modes, and blob hashes). If the build emitted only `index.js` while the commit
// also carried `README.md`, the exact-tree comparison would necessarily fail; this
// script therefore emits the READMEs too.
//
// Later epics replace the placeholder `index.js` emitters below with the real
// bundler (esbuild/ncc) for each adapter; the READMEs stay generated here so the
// exact-tree gate keeps working unchanged.
//
// All content is LF-only with a single trailing newline (byte-stable across
// platforms; `.gitattributes` also pins these paths to `eol=lf`).
//
// Run: `npm run build`

import { mkdirSync, writeFileSync, rmSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const REPO_ROOT = join(dirname(fileURLToPath(import.meta.url)), '..');

// Machine-detectable marker the release gates grep for to refuse publishing a
// placeholder. Assembled from fragments so this generator source is not itself
// mistaken for a built bundle carrying the sentinel.
const SENTINEL = ['__CHAOS_STUDIO', 'PLACEHOLDER', 'BUNDLE__'].join('_');

/** LF-only placeholder bundle for a surface. */
function placeholderBundle(surface, readmePath, builtFrom, epic) {
  return (
    `// Placeholder for the committed ${surface} runtime bundle.\n` +
    `//\n` +
    `// The real bundle is reproducibly built from ${builtFrom} and committed\n` +
    `// here by the release build in a later epic (${epic}). Until then this stub\n` +
    `// fails fast so a partially-wired ${surface} never runs silently.\n` +
    `//\n` +
    `// The sentinel below is the machine-detectable marker release pipelines grep\n` +
    `// for to refuse publishing a placeholder bundle. A real built bundle must not\n` +
    `// contain this token. Marker: ${SENTINEL}\n` +
    `//\n` +
    `// eslint-disable-next-line no-console\n` +
    `console.error(\n` +
    `  'Azure Chaos Studio ${surface}: the runtime bundle has not been built yet ' +\n` +
    `    '(${SENTINEL}). See ${readmePath}.',\n` +
    `);\n` +
    `process.exit(1);\n`
  );
}

const ACTION_README =
  `# \`dist/github-action/\` — committed GitHub Action bundle\n` +
  `\n` +
  `This directory holds the **reproducibly built, committed** runtime bundle that\n` +
  `the root [\`action.yml\`](../../action.yml) executes with the \`node24\` runtime\n` +
  `(VF16, VF17, D19). GitHub Marketplace consumers run this bundle directly, so it\n` +
  `is checked in rather than built on the fly.\n` +
  `\n` +
  `- **Source:** \`packages/action-github\` (thin \`@actions/core\` adapter over the\n` +
  `  shared core in \`packages/core\`).\n` +
  `- **Build:** produced by \`npm run build\` (\`scripts/build.mjs\`) and verified by a\n` +
  `  \`dist\`-integrity check that fails the build if the committed tree does not\n` +
  `  match a clean rebuild file-for-file (supply-chain hardening, D18).\n` +
  `\n` +
  `Both \`index.js\` and this \`README.md\` are generated by \`scripts/build.mjs\` so the\n` +
  `exact-tree integrity gate reproduces the whole directory. \`index.js\` is currently\n` +
  `a **placeholder stub** that fails fast; the adapter and its real bundle are wired\n` +
  `in a later epic (E3).\n`;

const TASK_README =
  `# \`dist/azure-pipelines-task/\` — committed Azure Pipelines task bundle\n` +
  `\n` +
  `This directory holds the **reproducibly built** runtime bundle for the Azure\n` +
  `Pipelines task. The OneBranch official pipeline copies this bundle into the task\n` +
  `folder under [\`azure-pipelines-extension/\`](../../azure-pipelines-extension/)\n` +
  `and packages it into the signed VSIX.\n` +
  `\n` +
  `- **Source:** \`packages/task-azure-pipelines\` (thin \`azure-pipelines-task-lib\`\n` +
  `  adapter over the shared core in \`packages/core\`).\n` +
  `- **Runtime:** the task uses the \`Node20_1\` execution handler (VF15, D19); a\n` +
  `  Node24 handler is added when Azure Pipelines ships one.\n` +
  `- **Build:** both \`index.js\` and this \`README.md\` are generated by\n` +
  `  \`npm run build\` (\`scripts/build.mjs\`) so the \`dist\`-integrity gate reproduces\n` +
  `  the whole directory.\n` +
  `\n` +
  `\`index.js\` is currently a **placeholder stub** that fails fast. The adapter and\n` +
  `its real bundle are wired in a later epic (E4).\n`;

// The COMPLETE committed dist tree. Every committed file under dist/ is produced
// here so the exact-tree integrity gate matches after a clean rebuild.
const FILES = [
  {
    path: 'dist/github-action/index.js',
    content: placeholderBundle('Action', 'dist/github-action/README.md', 'packages/action-github', 'E3+'),
  },
  { path: 'dist/github-action/README.md', content: ACTION_README },
  {
    path: 'dist/azure-pipelines-task/index.js',
    content: placeholderBundle('task', 'dist/azure-pipelines-task/README.md', 'packages/task-azure-pipelines', 'E4'),
  },
  { path: 'dist/azure-pipelines-task/README.md', content: TASK_README },
];

// Build into a clean dist/ so a stale file the build no longer emits cannot
// linger (the release/PR gate additionally rebuilds into an empty dir).
rmSync(join(REPO_ROOT, 'dist'), { recursive: true, force: true });
for (const file of FILES) {
  const full = join(REPO_ROOT, file.path);
  mkdirSync(dirname(full), { recursive: true });
  writeFileSync(full, file.content, 'utf8');
  console.log(`Wrote ${file.path}`);
}
